### PR TITLE
Update gems.

### PR DESCRIPTION
**Pull request by nbianca**

### CODE REVIEW

**Comment by nbianca** [comment]
I updated Rubocop rules to match the current coding style as best as possible and after that I formatted the files which violated the rules.

**Comment by ZogStriP** [comment]
@nbianca Looks like there's a conflict ;)

**Comment by nbianca** [comment]
Gerhard recently changed the style to follow Discourse's and I had to refix it.

@mpalmer Can you please check it again?

**Comment by mpalmer** [comment]
What the?  Rubocop is enforcing bad variable names now?  Not to mention reducing the readability of hashes?  Shut.  It.  Down.

**Comment by ZogStriP** [comment]
I agree, the variable name changes are weird.

**Comment by mpalmer** [comment]
The `r` => `record` one is a good one, but the conversion to single characters in the blocks is actively harmful, IMO.

**Comment by nbianca** [comment]
Rubocop does not like shadowing variables. I chose to go with single name variable names just because those are usually used while iterating and is clear what the variable means.

I do not have a better idea for a scheming name other than something like `txt_` instead of `txt`.

**Comment by mpalmer** [comment]
Personally, I'd prefer to override whatever it is in the default config that's causing those rubocop complaints, unless it's considered Generally Acceptable to change them in the default.  Apart from the `r` => `record` change (which is a good one, and should be kept, but in a separate commit from "update ALL THE GEMS!"), I think all those rubocop-mandated changes are actively bad for readability.

**Pull request closed without merging**
